import fs from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';

import { env } from '../../config/env.js';

/**
 * Files on a local filesystem. In production that path is an attached disk, so
 * the same driver serves both; swapping to object storage means adding a
 * sibling module with this shape and choosing it in `index.js`.
 */
const root = path.resolve(env.uploadDir);

// A storage key is generated by us, never taken from the client, but a
// traversal here would let a bug become a file write anywhere on the host.
const resolveKey = (key) => {
  const full = path.resolve(root, key);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error('Refusing a storage key that escapes the upload directory.');
  }
  return full;
};

export const driver = 'local';

export const ensureReady = async () => {
  await fs.mkdir(root, { recursive: true });
};

export const put = async (key, buffer) => {
  const full = resolveKey(key);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, buffer);
  return { key, bytes: buffer.length };
};

export const get = async (key) => fs.readFile(resolveKey(key));

export const stream = (key) => createReadStream(resolveKey(key));

export const stat = async (key) => {
  try {
    const info = await fs.stat(resolveKey(key));
    return { bytes: info.size, modifiedAt: info.mtime };
  } catch {
    return null;
  }
};

export const remove = async (key) => {
  try {
    await fs.unlink(resolveKey(key));
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return false;
    throw err;
  }
};

/**
 * Public media is served through the API rather than as static files so that
 * the private/public distinction is enforced in one place — an applicant's
 * passport scan must never become reachable by guessing a path.
 */
export const publicUrl = (key) => `/api/media/file/${key}`;
